language: php

php:
  - 7.3

cache:
  directories:
    - .composer/cache

before_install:
  - alias composer=composer\ --no-interaction && composer selfupdate

install:
  - travis_retry composer update --no-progress --no-suggest
    
script:
  - bin/grumphp run
